/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class intellif_minning_dbscan_impl_DBSCANImpl */

#ifndef _Included_intellif_minning_dbscan_impl_DBSCANImpl
#define _Included_intellif_minning_dbscan_impl_DBSCANImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     intellif_minning_dbscan_impl_DBSCANImpl
 * Method:    initDatasFromFile
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_intellif_minning_dbscan_impl_DBSCANImpl_initDatasFromFile
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     intellif_minning_dbscan_impl_DBSCANImpl
 * Method:    runDBSCAN
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_intellif_minning_dbscan_impl_DBSCANImpl_runDBSCAN
  (JNIEnv *, jobject, jfloat, jint);

/*
 * Class:     intellif_minning_dbscan_impl_DBSCANImpl
 * Method:    saveDBSCAN
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_intellif_minning_dbscan_impl_DBSCANImpl_saveDBSCAN
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
