drop table if exists default.dwd_bigdata_event_face_5029 ;
create table default.dwd_bigdata_event_face_5029(
 sys_code STRING,
 thumbnail_id STRING,
 thumbnail_url STRING,
 image_id STRING,
 image_url STRING,
 feature_info BINARY,
 algo_version INT,
 gender_info STRING,
 age_info STRING,
 hairstyle_info STRING,
 hat_info STRING,
 glasses_info STRING,
 race_info STRING,
 mask_info STRING,
 skin_info STRING,
 pose_info STRING,
 quality_info FLOAT,
 target_rect STRING,
 target_rect_float STRING,
 target_thumbnail_rect STRING,
 land_mark_info STRING,
 source_id BIGINT,
 source_type INT,
 site BIGINT,
 time TIMESTAMP,
 feature_quality FLOAT,
 create_time TIMESTAMP,
 save_time TIMESTAMP,
 column1 STRING,
 column2 STRING,
 column3 STRING
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' ;