/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CudaDBSCAN */

#ifndef _Included_CudaDBSCAN
#define _Included_CudaDBSCAN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CudaDBSCAN
 * Method:    runDBSCAN
 * Signature: (Ljava/util/List;FI)V
 */
JNIEXPORT void JNICALL Java_CudaDBSCAN_runDBSCAN
  (JNIEnv *, jobject, jobject, jint, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif